haproxy/downstream.go

Changed 'downstream' configuration so that when Intentations are enabled, a 'tcp-request content reject' is added instead of a 'tcp-request content accept'. That way, messages are rejected unless the Intention approves them. 
Currently, as-is, all messages are accepted regardless of the Intention rules. 
I have tested this by adding 'accept' and 'deny' Intentions and making a call from one proxy to an upstream. I also tested if this works when the ACL default_policy is either 'allow' or 'deny'.

Fixes #2 - Changed 'tcp-request content accept' to 'tcp-request content reject'

---

consul/logger.go
consul/logger_testing.go
consul/watcher.go
haproxy/haproxy_cmd/run.go
main.go
utils_test.go

This will allow to replace log implementation by testing one
to include tests into the Consul repository without adding
a new dependency

Use interface to log in Consul package

---

haproxy/haproxy_cmd/cmd.go
haproxy/haproxy_cmd/cmd_test.go
haproxy/haproxy_cmd/run.go

In order to properly detect dataplaneapi/haproxy not launching, `cmd.Process != nil` needs to be checked as documented in Go APIs.

[BUGFIX] Properly detect failure to launch process

---

haproxy/config.go
haproxy_test.go
utils_test.go

In the case where the Process dataplaneapi was not activated for instance, the process was hanging forever.
Combined with https://github.com/haproxytech/haproxy-consul-connect/pull/21 it will stop the test immediately if dataplaneapi or haproxy are not in the path

When test went wrong, test was not stopping properly.

---

haproxy/state/from_ha_test.go
haproxy/state/state.go

This test was sensitive to the way dataplance/haproxy is sorting backends/frontends.
Fix that to sort before comparing

BUGFIX Fix unstable unit test TestFromHA

---

haproxy/haproxy.go
haproxy/haproxy_cmd/run.go
haproxy/state/from_ha_test.go
main.go

when HAProxy is run with -version, it will also check for its external dependencies
Also skip the test with a message if those binaries are not present

FEATURE Check dataplaneapi and haproxy binaries

---

.travis.yml
haproxy_test.go

For now, the full test (aka run with binaries is not yet launched)

BUILD: ensure GNUMakefile is used, so unit tests are run

---

haproxy/haproxy_cmd/run.go

`cmd.CombinedOutput()` already start the process, there is not need
for Run()

BUG fix double execution of processes

---

consul/config.go
consul/watcher.go
haproxy/state/downstream.go
haproxy/state/upstream.go

New frontends and backends only had support for using models.FrontendModeHTTP
and models.BackendModeHTTP which limited them to "mode http" only. This commit
adds support for "mode tcp" using both upstream and downstream specific
configuration options. It defaults to http.
To use add a "config" option within an upstream similar to the below example:
Sample downstream service file for Redis
{
"service": {
"name": "redis",
"port": 6379,
"connect": {
"sidecar_service": {
"proxy" : {
"config": { "protocol" : "tcp" }
}
}
}
}
}
Sample upstream configuration:
"upstreams": [{
"destination_name": "redis",
"local_bind_port": 6379,
"config": { "protocol" : "tcp" }
}

MEDIUM: Add support for "mode tcp"

---

consul/config.go
consul/watcher.go
haproxy/state/downstream.go
haproxy/state/utils.go

This adds an option to enable X-Forwarded-For in the downstream backend.
This allows for the destination app to know where the request originated
from.
Example config :
```
{
"service": {
"name": "socat",
"port": 8181,
"connect": {
"sidecar_service": {
"proxy": {
"config": {
"enable_forwardfor": true
}
}
}
}
}
}
```
In Addition this fixes how the proxy options are read.

Add enable_forwardfor option

---

go.mod

with https://github.com/haproxytech/haproxy-consul-connect/commit/6a6fdaa29e3779376c5b7c75934c0142c1971458 commit
Milliseconds() is used. Since it is a Go 1.13 feature, Go min. version is updated from 1.12 to 1.13 in go.mod file

MAJOR: go-version: update Go min. version

---

haproxy/config.go

This change previously hard coded password ("insecure-password" in HAProxy config) usage and instead use hashed password("password").
So, on every start up a random password is generated, hashed and then saved to HAProxy conf.
Generated password is stored in memory, while hashed password is saved to HAProxy conf.

FEATURE/MEDIUM: userList: generate random secure password

---

haproxy/spoe.go

Addtionnal TLS verification done in SPOE was causing problem as the
haproxy fetch methods currently do not provide the full certificate
chain.
Since TLS verification was already enabled on haproxy side this just
removes the additional verification done in SPOE.
Fixes: #11

Disable TLS verification from SPOE

---

haproxy/haproxy_cmd/run.go

`Find` func accepts slice array and since `out` variable satisfies this,
there is no need for additional `[]byte(out)` call.

CLEANUP: environment-check: remove redundant slice

---

haproxy/haproxy_cmd/run.go

Since only one error is captured, there is no need for `make([]error, 2)` and index logic.
Instead, last error is captured and returned.
Additionally, `sync.WaitGroup` exists, but there was no goroutines spawned.
So, added `go` keyword to spawn goroutines.

CLEANUP: environment-check: dependent executables error logic refactored

---

consul/config.go
consul/watcher.go
haproxy/state/snapshot_test.go
haproxy/state/upstream.go
haproxy_test.go
utils_test.go

This adds support for prepared queries destinations in addition to
service ones: an upstream can now target a prepared query and benefit
from features such as fallback between DCs.
Since prepared queries do not support bloquing requests this uses polling
to periodically check for changes. The default polling rate is 30s: the
same as the one consul uses, and can be overriden with the "poll_interval"
config option.

Add support for prepared queries

---

README.md

based on https://github.com/haproxytech/haproxy-consul-connect/issues/5

Add minimal working example (credits to ShimmerGlass)

---

haproxy/state/apply.go
haproxy/state/apply_backend_test.go

When certificates changed servers where only updated, which didn't
change the certificates. This fixes it by recreating the backend on
certificate update.

Fix: recreate backends when certificates change

---

haproxy/state/from_ha_test.go
haproxy/state/snapshot_test.go
haproxy/state/upstream.go

Fix a bug that kept old certificates in server backends on existing
servers.

Fix: new certificates not upgraded on existing servers

---

haproxy/config.go

Reuse tcp connections to reduce tcp / tls handlshakes.

Set http-reuse always by default

---

go.mod
go.sum
haproxy/spoe.go

With intentions enabled, a lot of time is spent parsing the client
certificate and calling consul.
This adds a cache for both, taking care of in flight requests resulting
in much better performance.

Intentions: Add cache for Consul authorization and certificate parsing

---

haproxy/dataplane/backend.go
haproxy/dataplane/dataplane.go

Fix an issue where the config version in the dataplane api and
haproxy-connect could desync, causing all subsequent update call to
fail.
Now, before each operation, we check the current config version to
ensure we are synced.

Get current config version before update operations

---

haproxy/certs.go
haproxy/config.go
haproxy/dataplane/dataplane.go
haproxy/haproxy.go
haproxy/haproxy_cmd/cmd.go
haproxy/haproxy_cmd/cmd_test.go
haproxy/haproxy_cmd/run.go
haproxy_test.go

Some function calls were lacking error checking. This properly checks
these errors.

Add error checks where missing

---

haproxy/config.go
haproxy/haproxy.go
haproxy/state.go
haproxy/stats/metrics.go
haproxy/stats/stats.go

In some setup, we'd like to wait until connect is ready before running
the app. This PR adds a /ready endpoint that blocks until haproxy is
setup. A /health endpoint is also added to monitor that consul connect
is running.

Add /health and /ready endpoint to stats server

---

consul/config.go
consul/watcher.go
consul/watcher_test.go

Add unit tests to Consul watcher.
Fix the following things in the Consul watcher : 
* Bind upstreams on 127.0.0.1 by default
* Fix read timeout using connect timeout value

BUG/MINOR: fix watcher upstream bind and timeout value

---

haproxy/config.go

The default 4040 value is not enough for high load situations

Raise ulimit-n to 65536
